version: '3'

services:
  dns:
    image: chaiyd/dns:1.2
    environment:
      DOMAIN: "xxx.com"
      NS: |-
        ns		                  IN	    A	  192.168.1.10
        \nkubernetes            IN      A   192.168.1.10
        \nkubernetes            IN      A   192.168.1.10
        \nkubernetes            IN      A   192.168.1.10
        
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
