version: '3'

services:
  dns:
    image: chaiyd/dns:1.1
    environment:
      DOMAIN: "baidu.com"
      NS: |-
        ns        A   192.168.1.1
        \nceshi   A   192.168.1.1
        \nce      A   192.168.1.1
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"